// Screens that broke the copy rules before the scan in ui-copy.test.ts existed, with how many
// violations each has. A file listed here may not get worse; a file not listed may not have any.
// The sweep that rewrites these screens empties this list, one file at a time as each is clean.
//
// When the test fails, its message prints the current count for every file. Paste a file in
// here only on purpose, and never raise a count.

export const UI_COPY_BASELINE: Record<string, number> = {
  'app/(app)/companies/[id]/page.tsx': 1,
  'app/(app)/companies/page.tsx': 1,
  'app/(app)/copilot/dev-markdown-fixture/page.tsx': 5,
  'app/(app)/copilot/page.tsx': 4,
  'app/(app)/error.tsx': 1,
  'app/(app)/insights/page.tsx': 4,
  'app/(app)/jobs/page.tsx': 4,
  'app/(app)/notifications/page.tsx': 1,
  'app/(app)/pipeline/page.tsx': 4,
  'app/(app)/queue/page.tsx': 2,
  'app/(app)/resume/[jobId]/page.tsx': 5,
  'app/(app)/resume/page.tsx': 6,
  'app/(app)/settings/access/page.tsx': 1,
  'app/auth/callback/route.ts': 2,
  'app/layout.tsx': 1,
  'app/login/page.tsx': 3,
  'app/not-found.tsx': 1,
  'components/companies/add-company-dialog.tsx': 2,
  'components/contacts/contact-network-panel.tsx': 1,
  'components/contacts/csv-import.tsx': 6,
  'components/copilot/composer.tsx': 1,
  'components/copilot/graph-view.tsx': 1,
  'components/copilot/observation-view.tsx': 9,
  'components/copilot/runs-panel.tsx': 3,
  'components/copilot/step-card.tsx': 3,
  'components/dashboard/budget-meter-card.tsx': 1,
  'components/dashboard/gmail-sync-card.tsx': 1,
  'components/insights/digest-card.tsx': 3,
  'components/insights/funnel-bar.tsx': 1,
  'components/insights/provenance-mix-card.tsx': 4,
  'components/insights/source-performance-card.tsx': 1,
  'components/insights/strategy-panel.tsx': 4,
  'components/insights/whats-working.tsx': 1,
  'components/jobs/visa-badge.tsx': 3,
  'components/pipeline/log-application-dialog.tsx': 1,
  'components/pipeline/utils.ts': 1,
  'components/queue/batch-approve.tsx': 14,
  'components/queue/draft-card.tsx': 4,
  'components/queue/handoff-card.tsx': 1,
  'components/queue/queue-list.tsx': 2,
  'components/resume/markdown-editor.tsx': 1,
  'components/resume/markdown-toolbar.tsx': 3,
  'components/resume/resume-download-menu.tsx': 3,
  'components/resume/resume-optimizer-panel.tsx': 5,
  'components/resume/resume-preview.tsx': 2,
  'components/settings/access-code-activity.tsx': 1,
  'components/settings/access-codes-card.tsx': 5,
  'components/settings/api-keys-tab.tsx': 4,
  'components/settings/connections-tab.tsx': 9,
  'components/settings/mcp-tab.tsx': 6,
  'components/settings/model-tab.tsx': 5,
  'components/settings/provider-tab.tsx': 2,
  'components/settings/search-tab.tsx': 7,
  'components/settings/sources-tab.tsx': 10,
  'components/settings/targeting-tab.tsx': 1,
  'components/settings/tokens-tab.tsx': 4,
}
