// The register of 13.1: every measure Cello keeps, with its bar and where its number comes from.
// K7 seeds each row as 'watch' (migration 20261008045000); the package named in `gates` flips its rows
// to 'gating' when it ships. A test keeps this list equal to the migration's inserts.

export type MeasureLayer = 'true' | 'step' | 'person'
export type MeasureDirection = 'higher' | 'lower' | 'equal' | 'reported'

export interface MeasureDef {
  id: string
  layer: MeasureLayer
  name: string
  bar: string
  /** Which way is better, for the trend; 'reported' has no bar yet or none that is a number. */
  direction: MeasureDirection
  /** Where the number comes from. */
  source: string
  /** The packages that this measure gates. */
  gates: string[]
}

export const REGISTER: readonly MeasureDef[] = [
  {
    id: 'T1',
    layer: 'true',
    name: 'wrong-employer roles stored',
    bar: '0',
    direction: 'equal',
    source: 'live check-sourcing.ts on every followed employer',
    gates: ['K6'],
  },
  {
    id: 'T2',
    layer: 'true',
    name: 'roles shown older than 180 days',
    bar: '0',
    direction: 'equal',
    source: 'SQL over shown lists',
    gates: ['K5a'],
  },
  {
    id: 'T3',
    layer: 'true',
    name: "stored roles outside every person's targets (no-target rows counted apart)",
    bar: '0',
    direction: 'equal',
    source: 'SQL (directive 26)',
    gates: ['K5a'],
  },
  {
    id: 'T4',
    layer: 'true',
    name: 'followed employers that cannot be read',
    bar: 'under 5 percent, each with a reason',
    direction: 'lower',
    source: 'heartbeats',
    gates: ['K4'],
  },
  {
    id: 'T5',
    layer: 'true',
    name: 'hours since the last successful role check, per person',
    bar: 'at most 7',
    direction: 'lower',
    source: 'job_heartbeats',
    gates: ['K4'],
  },
  {
    id: 'T6',
    layer: 'true',
    name: 'hours since the last successful mail read, per connected person',
    bar: 'at most 2',
    direction: 'lower',
    source: 'job_heartbeats',
    gates: ['K19'],
  },
  {
    id: 'T7',
    layer: 'true',
    name: 'rows and bytes per person per table after a day of checks, no-target rows apart, description_md bytes on their own',
    bar: 'reported; owner sets the bar after the first week',
    direction: 'reported',
    source: 'catalog sizes',
    gates: [],
  },
  {
    id: 'T8',
    layer: 'true',
    name: 'database size, with description_md bytes on their own',
    bar: 'under 350 MB',
    direction: 'lower',
    source: 'catalog',
    gates: [],
  },
  {
    id: 'T9',
    layer: 'true',
    name: "companies Cello followed for a person: watching = true not set by companies.follow from that person's session, plus company_directory rows that did not pass the verifier",
    bar: '0',
    direction: 'equal',
    source: 'SQL',
    gates: ['K5a', 'K6', 'K19'],
  },
  {
    id: 'T10',
    layer: 'true',
    name: 'unconfirmed events moving a count',
    bar: '0',
    direction: 'equal',
    source: 'SQL over counts',
    gates: ['K13'],
  },
  {
    id: 'T11',
    layer: 'true',
    name: 'directory full-cycle days',
    bar: 'reported, no bar until SP6',
    direction: 'reported',
    source: 'heartbeats',
    gates: [],
  },
  {
    id: 'T12',
    layer: 'true',
    name: 'numbers on screen traced to code',
    bar: 'every one, in the pull request',
    direction: 'equal',
    source: 'review',
    gates: [],
  },
  {
    id: 'T13',
    layer: 'true',
    name: "filled values equal to the person's own values",
    bar: "every fixture field; at least 0.98 on the owner's real sends, 0 wrong in a sensitive field",
    direction: 'equal',
    source: "fill fixtures in CI, then attempts against the owner's record",
    gates: ['K18', 'K21'],
  },
  {
    id: 'T14',
    layer: 'true',
    name: 'automatic sends marked Sent without a seen confirmation',
    bar: '0',
    direction: 'equal',
    source: 'attempts and events',
    gates: ['K21', 'K30'],
  },
  {
    id: 'T15',
    layer: 'true',
    name: 'a second submit for one application',
    bar: '0',
    direction: 'equal',
    source: 'submission.sending events',
    gates: ['K21', 'K30'],
  },
  {
    id: 'T16',
    layer: 'true',
    name: 'Send for me stops handed to the person with their cause and never retried',
    bar: 'every one',
    direction: 'equal',
    source: 'stop fixtures, then events',
    gates: ['K21', 'K30'],
  },
  {
    id: 'T17',
    layer: 'true',
    name: 'duplicate stored roles (same employer and requisition id, or normalised title and location)',
    bar: '0',
    direction: 'equal',
    source: 'SQL',
    gates: ['K5a'],
  },
  {
    id: 'T18',
    layer: 'true',
    name: 'hours from posting to shown: followed employers; directory',
    bar: "at most 7; reported until SP6, then the owner's bar",
    direction: 'lower',
    source: 'posted_at against visible_since',
    gates: ['K4', 'K6'],
  },
  {
    id: 'T19',
    layer: 'true',
    name: 'share of new distinct titles decided by each tier (code, embedder, model, none); share of stored roles whose type needed a model; untyped stored roles',
    bar: 'model under 15 percent of new titles a week [X]; untyped under 2 percent of stored roles; reported weekly',
    direction: 'reported',
    source: 'title_types, jobs, roles.type heartbeats',
    gates: ['K15b', 'K5c'],
  },
  {
    id: 'T20',
    layer: 'true',
    name: 'while role_types_live is off: roles the type step would keep that the old filter drops, and the reverse, per person per day',
    bar: 'reported',
    direction: 'reported',
    source: 'person_counts (shadow_keep, shadow_drop)',
    gates: ['K5c'],
  },
  {
    id: 'T21',
    layer: 'true',
    name: "description completeness: share of kept roles whose stored posting is the employer's whole text, against a fresh read of the live page (token recall at least 0.98 [X]), on a weekly sample of 50 across tiers; partial postings with reasons; silent truncation",
    bar: 'at least 0.95 complete; partial reported; silent truncation 0',
    direction: 'higher',
    source: 'live re-read of the sample',
    gates: ['K5d'],
  },
  {
    id: 'T22',
    layer: 'true',
    name: 'page performance on a mid-range phone, per page (4.0a): LCP, Total Blocking Time, main-thread work, CLS, INP; the 3D chunk and first-load growth',
    bar: 'LCP at most 2.5 s; TBT at most 200 ms; main thread at most 2.0 s, the layer at most 150 ms; CLS at most 0.05; INP at most 200 ms; 3D chunk at most 200 KB gzipped, first-load growth at most 5 KB',
    direction: 'lower',
    source: 'Lighthouse CI and Playwright on fixtures in CI, then production weekly',
    gates: ['PG0'],
  },
  {
    id: 'T23',
    layer: 'true',
    name: "browsing an employer's open roles (companies.roles, roles.preview): jobs, person_roles and seen_postings rows written by browsing; the counted line's buckets against the read's total, on a weekly sample of 20 employers across tiers; share of reads that return a total or a named cannot-read reason",
    bar: '0 rows; equal on every sampled read; 1.0',
    direction: 'equal',
    source: 'SQL row counts before and after scripted browsing; live reads of the sample',
    gates: ['K5b', 'K5d', 'PG7'],
  },
  {
    id: 'T24',
    layer: 'true',
    name: "directory search coverage: the share of the owner's 35 real past employers (his trusted application history, S8's set) that companies.search returns by name among its first 3 verified rows; each miss with its reason (not in the seed, still pending, failed check, cannot read); the seed's verification progress",
    bar: 'at least 34 of 35, every miss named; progress reported',
    direction: 'higher',
    source: 'his 35 names run weekly; directory.sweep heartbeats',
    gates: ['K6', 'PG11'],
  },
  {
    id: 'T25',
    layer: 'true',
    name: "add by link: the right outcome on 20 real careers links the owner picks (careers pages, boards and single postings across providers, with Retell AI's careers page, a Workday host, a page with no board, a board another employer owns and an unused board among them): the right employer verified, added and followed, or Could not verify with the right reason and its offer",
    bar: '20 of 20; 0 wrong employers added',
    direction: 'reported',
    source: 'live runs of companies.add',
    gates: ['K6', 'PG11'],
  },
  {
    id: 'T26',
    layer: 'true',
    name: "autodiscovery fill: share of the seed's candidates verified or failed (not pending) within 30 days of the first directory.sweep slice; the first day's count projected to the whole seed",
    bar: "at least 0.9 in 30 days; K6's first day projects inside 30 days",
    direction: 'higher',
    source: 'directory_candidates states, sweep heartbeats',
    gates: ['K6', 'PG11'],
  },
  {
    id: 'T27',
    layer: 'true',
    name: 'boundary checks kept from main: every old address redirects to its new home; a page or plain read in hour 73 of a demo is refused and the session refreshes on each request; a cross-site POST to every session command is refused; the clock and runner routes refuse a missing or bad signature; stdio tools and local command-line models refuse unless isSelfHosted(); a planted server error reaches Sentry scrubbed',
    bar: 'every check passes',
    direction: 'equal',
    source: 'CI route and source tests',
    gates: ['K3', 'K4', 'K10', 'K25', 'PG1', 'PG9'],
  },
  {
    id: 'T28',
    layer: 'true',
    name: 'sponsorship lines: every "Past H-1B filings" shown is traced to h1b-sponsors.json; any "does not sponsor"',
    bar: 'every one; 0',
    direction: 'equal',
    source: 'source test and fixtures',
    gates: ['PG3', 'PG7', 'PG11'],
  },
  {
    id: 'T29',
    layer: 'true',
    name: "Chat's workings: task lines equal their agent_tasks rows (research, drafts, chance, starts and checks of several employers); a turn's shown cost equals its llm_spend sum; the model a turn ran on equals the choice, or ran names the step down; writes after Stop; time from Stop to stopped",
    bar: 'every one; every one; every one; 0; under 5 s [X]',
    direction: 'equal',
    source: 'fixtures, then production turns sampled weekly',
    gates: ['K24d', 'PG9'],
  },
  {
    id: 'T30',
    layer: 'true',
    name: 'Network extraction: of people network.sync kept, the share that are real people the owner has been in touch with about his search (not bots, bulk, relays or role inboxes); left-out counts by rule; real people found among 50 left out',
    bar: 'at least 0.95; recall reported',
    direction: 'higher',
    source: '100 kept and 50 left out from his 12 months, marked by him',
    gates: ['K26'],
  },
  {
    id: 'T31',
    layer: 'true',
    name: 'employer ties: share of people tied to the right employer and application; people whose employer came from a relay or a personal domain',
    bar: 'at least 0.95; 0',
    direction: 'higher',
    source: 'the same 100, marked by him',
    gates: ['K26'],
  },
  {
    id: 'T32',
    layer: 'true',
    name: "follow-up nudges on scripted threads (yours unanswered, theirs unanswered, a reply that answered, weekends, a zone change, a person's own rule, snooze, a closed application, two unanswered follow-ups, and a reply on Friday at 19:00, due Sunday at 19:00): due exactly when the rule says; any after the person answered",
    bar: 'every one; 0',
    direction: 'equal',
    source: "fixture threads on a fixture clock, then the owner's week",
    gates: ['K26', 'PG12'],
  },
  {
    id: 'T33',
    layer: 'true',
    name: "What is working: each finding's counts against hand counts on fixture events; unconfirmed events counted; findings shown below their threshold; a Keep that changes anything it does not name",
    bar: 'every one equal; 0; 0; 0',
    direction: 'equal',
    source: "fixture events in CI, then the owner's applications counted by hand",
    gates: ['K19', 'PG5'],
  },
  {
    id: 'S1',
    layer: 'step',
    name: 'requirements, item by item: precision (a real requirement of the posting, of the right kind) and quote rate (every quote verbatim in description_md)',
    bar: 'precision at least 0.90; quotes 1.0; recall reported',
    direction: 'higher',
    source: '50 postings the owner labels item by item',
    gates: ['K5d', 'K17'],
  },
  {
    id: 'S2',
    layer: 'step',
    name: "role types: precision and recall per type; recall of the keep decision on the owner's chosen types",
    bar: 'per type with at least 10 labels: precision and recall at least 0.90; keep recall at least 0.95; under 10 labels "Too few to tell"',
    direction: 'higher',
    source: "100 titles from the owner's kept roles and application history, labelled by him; then his corrections and 100 directory titles sampled per tier",
    gates: ['K5c', 'K15b'],
  },
  {
    id: 'S3',
    layer: 'step',
    name: 'chance band agreement; Strong-for-Stretch swaps',
    bar: 'at least 0.7; 0',
    direction: 'higher',
    source: '60 roles labelled by the owner',
    gates: ['K17'],
  },
  {
    id: 'S4',
    layer: 'step',
    name: 'picks: precision at 5 against code order',
    bar: 'a rise of at least 0.10',
    direction: 'higher',
    source: "the owner's held-out reactions",
    gates: ['K17'],
  },
  {
    id: 'S5',
    layer: 'step',
    name: 'tailoring: uncited lines; Reviewer pass',
    bar: '0; at least 0.8',
    direction: 'equal',
    source: "10 real postings, the owner's resume",
    gates: ['K17'],
  },
  {
    id: 'S6',
    layer: 'step',
    name: 'drafts pass code checks first try; invented claims',
    bar: 'at least 0.9; 0',
    direction: 'higher',
    source: 'outputs sets',
    gates: ['K17'],
  },
  {
    id: 'S7',
    layer: 'step',
    name: 'Reviewer catches planted invented claims',
    bar: 'at least 0.9',
    direction: 'higher',
    source: 'claims set',
    gates: ['K17'],
  },
  {
    id: 'S8',
    layer: 'step',
    name: "mail: precision of linked applications; recall against the owner's 35",
    bar: 'at least 0.95; at least 0.9',
    direction: 'higher',
    source: "the owner's mailbox, 12 months",
    gates: ['K19'],
  },
  {
    id: 'S9',
    layer: 'step',
    name: 'employer from email accepted wrongly',
    bar: '0',
    direction: 'equal',
    source: '100 owner mails',
    gates: ['K19'],
  },
  {
    id: 'S10',
    layer: 'step',
    name: 'answer category; sensitive recall; near pairs matched',
    bar: '0.9; 0.95; 0',
    direction: 'equal',
    source: '120 public questions',
    gates: ['K16'],
  },
  {
    id: 'S11',
    layer: 'step',
    name: 'rendered read: links not on the page; recall',
    bar: '0; at least 0.8',
    direction: 'equal',
    source: '20 pages',
    gates: ['K4'],
  },
  {
    id: 'S12',
    layer: 'step',
    name: 'embed recall at 5 over words-only',
    bar: 'above words-only',
    direction: 'higher',
    source: '50 queries',
    gates: [],
  },
  {
    id: 'S13',
    layer: 'step',
    name: 'research claims citing a fetched source',
    bar: '1.0',
    direction: 'equal',
    source: 'research set',
    gates: ['K24b'],
  },
  {
    id: 'S14',
    layer: 'step',
    name: "Chat command selection; person-only and injection writes, the injection set including Cello's own answer text quoted back by selection as if typed",
    bar: 'at or above a re-measured baseline; 0',
    direction: 'reported',
    source: 'Chat sets',
    gates: ['K24b'],
  },
  {
    id: 'S15',
    layer: 'step',
    name: "judge agreement with the owner's labels",
    bar: 'at least 0.8',
    direction: 'higher',
    source: '50 owner-labelled pairs per judged step',
    gates: ['K17', 'K24b'],
  },
  {
    id: 'S16',
    layer: 'step',
    name: 'learnings: reads used before Keep; planted instructions made active',
    bar: '0; 0',
    direction: 'equal',
    source: 'learning set',
    gates: ['K15'],
  },
  {
    id: 'S17',
    layer: 'step',
    name: 'agency and repost labels: precision',
    bar: 'at least 0.9',
    direction: 'higher',
    source: '50 roles labelled by the owner',
    gates: ['K6'],
  },
  {
    id: 'S18',
    layer: 'step',
    name: 'people.find "how sure" against checked emails',
    bar: 'stated sureness within 10 points of the observed rate per band',
    direction: 'reported',
    source: '50 emails the owner checks',
    gates: ['K26'],
  },
  {
    id: 'S19',
    layer: 'step',
    name: "each skill's eval set",
    bar: "the skill's own bar, set with its set",
    direction: 'reported',
    source: 'skill evals',
    gates: [],
  },
  {
    id: 'S20',
    layer: 'step',
    name: 'strengths and gaps: precision of Strength and of Gap; quotes found in their cited source; Not found (code) scored apart as the share the owner marks as held under other words, reported',
    bar: 'Strength at least 0.90, Gap at least 0.85; quotes 1.0',
    direction: 'reported',
    source: "30 of the owner's kept roles, each requirement's verdict marked by him",
    gates: ['K17b'],
  },
  {
    id: 'S21',
    layer: 'step',
    name: 'answers about many things: on 10 scripted asks over chats with 3 to 6 attached roles, companies, applications and people, the share of answer parts whose about names the right objects, and facts (numbers, dates, quotes) tied to the wrong object',
    bar: 'at least 0.95 of parts right; 0 facts on the wrong object',
    direction: 'higher',
    source: '10 asks the owner writes and labels part by part, run on R2 and R3',
    gates: ['K24b'],
  },
  {
    id: 'S22',
    layer: 'step',
    name: "recall across chats: on 10 scripted pairs (a first chat states a fact, makes a comparison or takes a decision; a later new chat with no tiles refers to it in words only), the right earlier item used and its source chat shown; recall from another person's chats",
    bar: 'at least 9 of 10 on R2 and R3; 0 from another person',
    direction: 'higher',
    source: '10 pairs the owner writes, on the demo seed and his own account',
    gates: ['K24c'],
  },
  {
    id: 'S23',
    layer: 'step',
    name: "name lookup (companies.resolve_name): on 10 company names the owner picks that companies.search cannot find, the employer's right domain proposed, and wrong employers added after the verifier",
    bar: 'at least 8 of 10; 0 wrong employers',
    direction: 'higher',
    source: '10 names he picks, run live on R1 and R2',
    gates: ['K6', 'PG11'],
  },
  {
    id: 'S24',
    layer: 'step',
    name: 'recent hires (later): share of people shown as recently hired whose cited page names them, the employer and a join date inside the window',
    bar: 'at least 0.95; 0 without a source',
    direction: 'higher',
    source: '30 the owner checks',
    gates: ['K31'],
  },
  {
    id: 'S25',
    layer: 'step',
    name: 'public profiles: share of kept profiles that are the right person, on 20 contacts the owner marks; profiles from behind a login or from a page Cello opened',
    bar: 'at least 0.9 (18 of 20); 0',
    direction: 'higher',
    source: '20 contacts he marks, run on R1 and R2',
    gates: ['K26'],
  },
  {
    id: 'S26',
    layer: 'step',
    name: 'person memories: quotes verbatim in their message; share the owner marks right; planted instructions in mail that change anything',
    bar: '1.0; at least 0.9 of 30; 0',
    direction: 'reported',
    source: '30 memories from his mail; a planted-mail set',
    gates: ['K26'],
  },
  {
    id: 'P1',
    layer: 'person',
    name: 'share of shown roles marked Interested; Not for me reasons that are role type, level or place',
    bar: 'rising over 6 weeks; under 10 percent',
    direction: 'higher',
    source: "the person's reactions",
    gates: [],
  },
  {
    id: 'P2',
    layer: 'person',
    name: 'edit size on drafts (diff-words-v1, median)',
    bar: 'falling; bar by the owner',
    direction: 'lower',
    source: 'feedback_events',
    gates: [],
  },
  {
    id: 'P3',
    layer: 'person',
    name: 'minutes per application, Ready to sent',
    bar: 'bar by the owner',
    direction: 'reported',
    source: 'fill and submission events',
    gates: [],
  },
  {
    id: 'P4',
    layer: 'person',
    name: "replies and interviews per 10 applications against the person's email history before Cello",
    bar: 'above the baseline',
    direction: 'higher',
    source: 'trusted events and the pre-Cello mailbox',
    gates: [],
  },
  {
    id: 'P5',
    layer: 'person',
    name: 'free requests per active day; days hitting the 429; Needs you rows that waited for the limit; share using each door',
    bar: 'reported',
    direction: 'reported',
    source: 'llm_spend',
    gates: [],
  },
  {
    id: 'P6',
    layer: 'person',
    name: 'a no-model person completes Welcome, reacts, applies as is, fills, tracks a reply, sees Results',
    bar: 'passes',
    direction: 'reported',
    source: 'task test',
    gates: ['PG1', 'PG5'],
  },
  {
    id: 'P7',
    layer: 'person',
    name: 'the owner clears Needs you in under 3 minutes and flags no row as wrong in a week',
    bar: 'passes',
    direction: 'reported',
    source: "owner's days",
    gates: [],
  },
  {
    id: 'P8',
    layer: 'person',
    name: 'Chat page task success on the demo flows: the seven requests of 5.6, an empty chat\'s suggestion, switching the model for one message and reading its cost, opening a made thing in the side panel and saving an edit, stopping one worker, editing an earlier turn, a quick chat from a record, reopening an earlier chat\'s draft, attaching a second role and a company and removing one, referring to an earlier chat with "@" (a chip in the composer, a tile once sent, and a chip removed before sending attaches nothing), following a made thing to its object with its provenance',
    bar: 'every flow passes scripted on R2 and R3; 4 of 5 strangers finish each unaided',
    direction: 'equal',
    source: 'demo seed, stranger sessions',
    gates: ['PG9'],
  },
  {
    id: 'P9',
    layer: 'person',
    name: 'the taste panel on the dimensional layer (4.0a), per page at 390 and 1440, WebGL on and off',
    bar: 'the owner says yes on every page; 0 blocking tells from either reviewer',
    direction: 'reported',
    source: 'the owner and both reviewers',
    gates: ['PG0'],
  },
]
