// Types for public.resume_documents — versioned resume documents.
//
// Mirrors supabase/migrations/20260724000002_phaseB.sql. The table is NOT in
// @cello/shared's generated `Database` type, so lib/resume/store.ts talks to it
// through an untyped Supabase client with the row shapes declared here (the same
// convention as lib/interview/store.ts and lib/dossier/store.ts).
//
// THE VERSIONING MODEL
//   Rows are append-only snapshots. A "bucket" is a (user_id, job_id) pair:
//     job_id === null  -> the BASE resume (the user's master document)
//     job_id === <uuid> -> resumes TAILORED for that one job
//   `version` is 1-based and monotonic *within a bucket*, so the base resume and
//   each job's tailored resume each have their own independent v1, v2, v3...
//   Never mutate `content` in place — create a new version so the studio can
//   diff and roll back.

/**
 * Provenance of a version. Enforced in TypeScript only — the column has no CHECK
 * constraint, so adding a value here needs no migration.
 *   base     — imported/parsed from the user's uploaded resume (profiles.resume_text)
 *   tailored — generated by an agent for a specific job
 *   edited   — the user hand-edited a previous version in the studio
 */
export type ResumeSource = 'base' | 'tailored' | 'edited'

export const RESUME_SOURCES = ['base', 'tailored', 'edited'] as const

/** Narrowing guard for values arriving from the DB or a request body. */
export function isResumeSource(value: unknown): value is ResumeSource {
  return typeof value === 'string' && (RESUME_SOURCES as readonly string[]).includes(value)
}

/** One structured section of a resume, when `content_json` is populated. */
export interface ResumeSection {
  /** e.g. "Experience", "Skills", "Education". */
  heading: string
  /** Body lines / bullets, in order. May be empty. */
  bullets: string[]
}

/**
 * Optional structured mirror of `content`, stored in `content_json`.
 * ALWAYS nullable — `content` (plain text) is the source of truth and the thing
 * an ATS receives. Every read path must tolerate a null `content_json`.
 *
 * FORMATTING LIVES HERE, AND IT NEEDED NO MIGRATION
 *   `markdown` and `templateId` are ordinary keys under the free-form index
 *   signature above, inside the existing jsonb column. Nothing in the schema
 *   changed, and every existing row — which has content_json = null — keeps
 *   working: it simply has no markdown and no chosen template yet.
 *
 * WHICH ONE IS AUTHORED AND WHICH IS DERIVED (read this before writing either)
 *   `content_json.markdown` is AUTHORED. It is what the user types in the
 *   studio and what the templates render.
 *   `content` is DERIVED: it is `markdownToPlainText(markdown)` from
 *   lib/resume/markdown.ts, and it stays plain text forever because it is what
 *   an ATS and every apply path consume.
 *   NEVER edit the two independently. Writing `content` by hand while leaving
 *   `markdown` alone (or vice versa) makes the exported PDF and the text the
 *   employer's parser reads describe different resumes, which is exactly the
 *   silent-corruption failure this contract exists to prevent. Write both
 *   together — see toResumeContentJson() below.
 *   A row with `content` but no `markdown` is legal and means "plain text,
 *   never formatted"; treat the plain text as the initial Markdown.
 */
export interface ResumeContentJson {
  sections?: ResumeSection[]
  /**
   * The AUTHORED, formatted resume. Markdown parsed by remark (headings 1-3,
   * paragraphs, ordered/unordered lists, rules, and inline bold/italic/code/
   * links). Absent on every row written before formatting shipped.
   */
  markdown?: string
  /**
   * Id of the chosen template from lib/resume/templates.ts. Unknown or absent
   * ids degrade to DEFAULT_TEMPLATE_ID via getTemplate() — a stored id must
   * never be able to break a render, so this stays a plain string rather than
   * a union that a retired template would make unassignable.
   */
  templateId?: string
  /** Free-form room for future structure without another migration. */
  [key: string]: unknown
}

/**
 * The authored Markdown for a version, or null when there is none.
 * Tolerates a null/undefined content_json and a non-string stored value —
 * this reads user data out of a jsonb column, so nothing is guaranteed.
 */
export function getResumeMarkdown(
  contentJson: ResumeContentJson | null | undefined
): string | null {
  const value = contentJson?.markdown
  return typeof value === 'string' && value.length > 0 ? value : null
}

/**
 * The stored template id, or null. Callers pass the result straight to
 * getTemplate(), which owns the fallback — do NOT default it here, or two call
 * sites will eventually disagree about what the default is.
 */
export function getResumeTemplateId(
  contentJson: ResumeContentJson | null | undefined
): string | null {
  const value = contentJson?.templateId
  return typeof value === 'string' && value.length > 0 ? value : null
}

/**
 * The Markdown to open in the editor for a version. Falls back to the derived
 * plain text, because every resume stored before this feature is plain text and
 * plain text is valid Markdown — it lowers to paragraphs with its line
 * structure intact.
 */
export function resolveResumeMarkdown(doc: {
  content: string
  content_json: ResumeContentJson | null
}): string {
  return getResumeMarkdown(doc.content_json) ?? doc.content ?? ''
}

/**
 * Build the content_json for a new version without clobbering other keys an
 * earlier version may have set (e.g. `sections`). Pair it with the plain text
 * from markdownToPlainText(markdown) when calling createVersion() — writing one
 * without the other is the divergence described on ResumeContentJson.
 */
export function toResumeContentJson(
  markdown: string,
  templateId: string,
  base?: ResumeContentJson | null
): ResumeContentJson {
  return { ...(base ?? {}), markdown, templateId }
}

/** Row shape of public.resume_documents (hand-declared; not in Database type). */
export interface ResumeDocument {
  id: string
  user_id: string
  /** null = the base resume; a uuid = tailored for that job. */
  job_id: string | null
  /** Optional back-pointer to the application_drafts row this was made for. */
  draft_id: string | null
  /** 1-based, monotonic within the (user_id, job_id) bucket. */
  version: number
  title: string | null
  /** Plain-text resume. Always present — this is what an ATS receives. */
  content: string
  /** Structured sections, or null when the version is plain text only. */
  content_json: ResumeContentJson | null
  /** 0-100, or null when this version has not been scored. */
  ats_score: number | null
  source: ResumeSource | null
  created_at: string
  updated_at: string
}

/**
 * Everything needed to append a new version. `version` is deliberately absent —
 * createVersion() computes it as max(version) + 1 for the bucket.
 */
export interface NewResumeVersion {
  userId: string
  /** null (or omitted) targets the BASE resume bucket. */
  jobId?: string | null
  draftId?: string | null
  title?: string | null
  content: string
  contentJson?: ResumeContentJson | null
  atsScore?: number | null
  source?: ResumeSource | null
}

/** Patchable fields on an existing version (metadata only, never `content`). */
export interface ResumeVersionPatch {
  title?: string | null
  atsScore?: number | null
}
