// Types for public.resume_documents — versioned resume documents.
//
// Mirrors supabase/migrations/20260724000002_phaseB.sql. The table is NOT in
// @cello/shared's generated `Database` type, so lib/resume/store.ts talks to it
// through an untyped Supabase client with the row shapes declared here (the same
// convention as lib/dossier/store.ts).
//
// THE VERSIONING MODEL
//   Rows are append-only snapshots. A "bucket" is a (user_id, job_id) pair:
//     job_id === null  -> the BASE resume (the user's master document)
//     job_id === <uuid> -> resumes TAILORED for that one job
//   `version` is 1-based and monotonic *within a bucket*, so the base resume and
//   each job's tailored resume each have their own independent v1, v2, v3...
//   Never mutate `content` in place — create a new version so the studio can
//   diff and roll back.

import type { Resume } from './schema'

/**
 * Provenance of a version. Enforced in TypeScript only — the column has no CHECK
 * constraint, so adding a value here needs no migration.
 *   base     — imported/parsed from the user's uploaded resume (profiles.resume_text)
 *   tailored — generated by an agent for a specific job
 *   edited   — the user hand-edited a previous version in the studio
 */
export type ResumeSource = 'base' | 'tailored' | 'edited'

export const RESUME_SOURCES = ['base', 'tailored', 'edited'] as const

/** Narrowing guard for values arriving from the DB or a request body. */
export function isResumeSource(value: unknown): value is ResumeSource {
  return typeof value === 'string' && (RESUME_SOURCES as readonly string[]).includes(value)
}

/**
 * The jsonb stored in `content_json`.
 *
 * ONE AUTHORED FIELD, EVERYTHING ELSE DERIVED (read this before writing any)
 *   `resume` is AUTHORED: a JSON Resume compatible document validated by
 *   ResumeSchema (./schema.ts). It is the only thing anything writes by intent.
 *   `markdown` is DERIVED: resumeToMarkdown(resume), with fixed heading levels
 *   (# name, ## section, ### entry). It is a cache for the preview and exports.
 *   `templateId` is DERIVED: resume.meta.cello.templateId, kept here for
 *   readers that only look at content_json.
 *   `content` (the column, not this object) is DERIVED: resumeToPlainText(resume).
 *   It stays plain text because it is what an ATS and every apply path read, and
 *   a database trigger mirrors the latest base version's `content` into
 *   profiles.resume_text.
 *   Nothing may write these separately. The only writer is createResumeVersion()
 *   in ./store.ts, which derives all of them from one validated Resume.
 *
 * LEGACY ROWS (written before `resume` existed) have only `markdown`/`templateId`
 * or are null. They are converted on read by resolveResume() in ./resolve.ts, so
 * no reader sees the difference.
 */
export interface ResumeContentJson {
  resume?: Resume
  /** Derived. Canonical fixed-level Markdown of `resume`. */
  markdown?: string
  /**
   * Derived. Id of the chosen template from lib/resume/templates.ts. Unknown or
   * absent ids degrade to DEFAULT_TEMPLATE_ID via getTemplate(), so this stays a
   * plain string rather than a union a retired template would make unassignable.
   */
  templateId?: string
  /** Free-form room for future structure without another migration. */
  [key: string]: unknown
}

/**
 * The derived Markdown for a version, or null when there is none. Tolerates a
 * null/undefined content_json and a non-string stored value: this reads user
 * data out of a jsonb column, so nothing is guaranteed.
 */
export function getResumeMarkdown(
  contentJson: ResumeContentJson | null | undefined
): string | null {
  const value = contentJson?.markdown
  return typeof value === 'string' && value.length > 0 ? value : null
}

/**
 * The stored template id, or null. Callers pass the result straight to
 * getTemplate(), which owns the fallback: do NOT default it here, or two call
 * sites will eventually disagree about what the default is.
 */
export function getResumeTemplateId(
  contentJson: ResumeContentJson | null | undefined
): string | null {
  const value = contentJson?.templateId
  return typeof value === 'string' && value.length > 0 ? value : null
}

/** Row shape of public.resume_documents (hand-declared; not in Database type). */
export interface ResumeDocument {
  id: string
  user_id: string
  /** null = the base resume; a uuid = tailored for that job. */
  job_id: string | null
  /** Optional back-pointer to the application_drafts row this was made for. */
  draft_id: string | null
  /** 1-based, monotonic within the (user_id, job_id) bucket. */
  version: number
  title: string | null
  /** Plain-text resume. Always present — this is what an ATS receives. */
  content: string
  /** Structured sections, or null when the version is plain text only. */
  content_json: ResumeContentJson | null
  /** 0-100, or null when this version has not been scored. */
  ats_score: number | null
  source: ResumeSource | null
  created_at: string
  updated_at: string
}

/** Patchable fields on an existing version (metadata only, never `content`). */
export interface ResumeVersionPatch {
  title?: string | null
  atsScore?: number | null
}
