-- Agent engine, part 3: scheduled tasks.
--
-- WHY
--   Recurring work is a Scheduled task: a saved instruction, a schedule and an
--   autonomy level. It runs as the same agent as the chat. There is no second
--   engine for it, and autopilot becomes one template of it (migration 607).
--
--   `cron` is generated by code from structured fields (lib/agents/scheduler.ts
--   toCron), never typed by the model. `next_run_at` is what the minute sweeper
--   reads (20261006000606): a due task is one whose next_run_at has passed.
--
-- Access: the owner can read their own tasks. All writes go through the API
-- (service role) so the next run time and the schedule always agree.

create table if not exists public.scheduled_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  instruction text not null check (char_length(instruction) between 1 and 2000),
  cron text not null check (char_length(cron) <= 80),
  timezone text not null default 'UTC' check (char_length(timezone) <= 64),
  -- ask: ask before every action; draft: draft everything, the person approves
  -- sends; act: act within the stored rules (never submits unless rules allow).
  autonomy text not null default 'ask' check (autonomy in ('ask', 'draft', 'act')),
  rules jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('active', 'paused')),
  template text check (template in ('find_roles', 'follow_up', 'autopilot')),
  -- The task's own conversation: every occurrence appends its result here.
  conversation_id uuid references public.copilot_conversations (id) on delete set null,
  next_run_at timestamptz,
  last_run_at timestamptz,
  last_status text check (last_status in ('ok', 'partial', 'failed', 'missed')),
  last_result text check (last_result is null or char_length(last_result) <= 500),
  -- Set when the sweeper pokes the continue endpoint, so a slow start is not poked twice.
  poked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_scheduled_tasks_due
  on public.scheduled_tasks (next_run_at) where status = 'active';
create index if not exists idx_scheduled_tasks_user
  on public.scheduled_tasks (user_id, created_at desc);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'copilot_conversations_scheduled_task_fk'
  ) then
    alter table public.copilot_conversations
      add constraint copilot_conversations_scheduled_task_fk
      foreign key (scheduled_task_id) references public.scheduled_tasks (id) on delete set null;
  end if;
end
$$;

alter table public.scheduled_tasks enable row level security;

drop policy if exists "own scheduled_tasks select" on public.scheduled_tasks;
create policy "own scheduled_tasks select" on public.scheduled_tasks
  for select to authenticated using ((select auth.uid()) = user_id);

revoke all on table public.scheduled_tasks from public, anon, authenticated;
grant select on table public.scheduled_tasks to authenticated;
grant all on table public.scheduled_tasks to service_role;

notify pgrst, 'reload schema';

do $$
begin
  if not exists (select 1 from pg_class where oid = 'public.scheduled_tasks'::regclass and relrowsecurity) then
    raise exception 'row level security is not enabled on scheduled_tasks';
  end if;
  if has_table_privilege('anon', 'public.scheduled_tasks', 'select') then
    raise exception 'anon must not read scheduled_tasks';
  end if;
end
$$;
